<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5OA9UT6" failures="1" tests="2" name="MyTestClass" time="10.478" errors="0" timestamp="2024-04-07T23:07:57 IST">
  <testcase classname="logintstcases.LoginTstCases" name="logintestcase" time="3.334"/>
  <testcase classname="logintstcases.LoginTstCases" name="moveTonextPage" time="0.048">
    <failure type="java.lang.AssertionError" message="expected [https://cloud-test.vendolite.com/portal/home] but found [https://cloud-test.vendolite.com/home/login]">
      <![CDATA[java.lang.AssertionError: expected [https://cloud-test.vendolite.com/portal/home] but found [https://cloud-test.vendolite.com/home/login]
at logintstcases.LoginTstCases.moveTonextPage(LoginTstCases.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- moveTonextPage -->
</testsuite> <!-- MyTestClass -->
